name: Test
on:
  push:
    branches-ignore:
      - 'master'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '**'

env:
  FORCE_COLOR: 2

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 18, 16]
    name: Node.js ${{ matrix.node-version }} unit and integration tests
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test:unit
    - run: npm run test:integration
